---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-hyades-frontend
  namespace: dependency-track
spec:
  template:
    spec:
      containers:
        - name: hyades-frontend
          env:
            - name: API_BASE_URL
              value: "https://dependency-track.localhost:30443"
