---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../vendor/helm

helmCharts:
  - name: postgresql
    version: 18.8.5
    repo: https://charts.bitnami.com/bitnami
    releaseName: postgresql
    namespace: postgresql
    valuesFile: values.yaml

secretGenerator:
  - name: postgresql-auth
    namespace: postgresql
    literals:
      - postgres-password=longpassword
      - password=dtrack

generatorOptions:
  disableNameSuffixHash: true
