---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/postgresql/overlays/dev
  - ../../platform/traefik/overlays/dev
  - ../../apps/dependency-track/overlays/dev

labels:
  - pairs:
      app.kubernetes.io/part-of: template-k8s
      environment: dev
    includeSelectors: false
    includeTemplates: true
