---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: dependency-track
    version: 2.0.0
    repo: https://dependencytrack.github.io/helm-charts
    releaseName: dependency-track
    namespace: dependency-track
    valuesFile: values.yaml

secretGenerator:
  - name: dependency-track-tls
    namespace: dependency-track
    type: kubernetes.io/tls
    files:
      - tls.crt=dependency-track.localhost+1.pem
      - tls.key=dependency-track.localhost+1-key.pem

generatorOptions:
  disableNameSuffixHash: true
