---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/services/postgresql/overlays/prod
  - ../../platform/services/observability/overlays/prod
  - ../../platform/controllers/traefik/overlays/prod
  - ../../apps/dependency-track/overlays/prod

labels:
  - pairs:
      app.kubernetes.io/part-of: template-k8s
      environment: prod
    includeSelectors: false
    includeTemplates: true
