---
common:
  database:
    jdbcUrl: "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/dtrack"
    username: "dtrack"
    password: "dtrack"

apiServer:
  service:
    type: ClusterIP
  metrics:
    enabled: false
  extraEnv: []

frontend:
  service:
    type: ClusterIP
  apiBaseUrl: "https://dependency-track.localhost"

ingress:
  enabled: true
