---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controllers
  - configs
  - apps

labels:
  - pairs:
      app.kubernetes.io/part-of: template-k8s
      environment: stage
    includeSelectors: false
    includeTemplates: true
