---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/services/postgresql/overlays/stage
  - ../../platform/controllers/traefik/overlays/stage
  - ../../apps/dependency-track/overlays/stage

labels:
  - pairs:
      app.kubernetes.io/part-of: template-k8s
      environment: stage
    includeSelectors: false
    includeTemplates: true
