---
service:
  type: LoadBalancer

ingressClass:
  name: traefik
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    disableAPICheck: true
    serviceMonitor:
      enabled: true
      namespace: observability

log:
  level: INFO
