---
service:
  spec:
    type: NodePort

ingressClass:
  name: traefik
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

log:
  level: INFO

hostNetwork: false

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
