apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/dependency-track
  - ../../../base/postgresql
  - ../../../base/traefik

# Patches to adapt Traefik for a remote (EKS) cluster
patches:
  - path: patch-traefik-service-loadbalancer.yaml
  - path: patch-traefik-deployment-hostnetwork-false.yaml
