---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus-rules.yaml

configMapGenerator:
  - name: dependency-track-grafana-dashboard
    namespace: observability
    files:
      - dependency-track-observability.json
      - dependency-track-sre-strategies.json
    options:
      labels:
        app.kubernetes.io/name: dependency-track
        app.kubernetes.io/part-of: dependency-track
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
