---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../../vendor/helm

helmCharts:
  - name: traefik
    version: 41.1.0
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    valuesInline:
      metrics:
        prometheus:
          disableAPICheck: true

patches:
  - path: patch-service-loadbalancer.yaml
  - path: patch-deployment-hostnetwork-false.yaml
